name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  REPO: ${{ github.repository }}


jobs:
  changed_containers:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.containers }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List Dockerfile changes
        id: matrix
        run: |
          bash ./scripts/changed-containers.sh \
            "${{ github.event.before }}" \
            "${{ github.sha }}" \
             >> $GITHUB_OUTPUT

      - name: Output changed containers
        run: |
          echo "${{ steps.matrix.outputs.containers }}"

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: [changed_containers]
    strategy:
      matrix:
        value: ${{fromJSON(needs.changed_containers.outputs.matrix.containers)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: |
          echo "${{ matrix.value }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker image labels
        id: meta
        run: |
          bash ./scripts/image-tag.sh \
            "${{ matrix.value }}" \
            >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: "${{ matrix.value }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ env.REGISTRY }}/${{ env.REPO }}/${{ matrix.value }}:${{ steps.meta.outputs.version }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
